### ISSUE TITLE
Function documentation

### ISSUE THREAD

**Issue by Boruch-Baum** [felipesaa/A-vim-like-firefox-like-configuration-for-w3m#2]
Hi. Thanks for this. I found out about it because I was following the w3m repo, and you were considerate to post there. From my initial scan, your work is helpful, and I hope it can somehow be pulled into the w3m project for everyone's use - the keymaps AND especially the documentation. Here are a few comments about the file 'functions.txt'

1) pendant - In English, a noun for a piece of jewelry, not an adjective, (but maybe it is in French?). You may have meant 'pending'.

2) leyend - should be 'legend'

3) I'm attaching the cheat sheet I currently use for w3m, in case it gives you any ideas or can be maybe be useful. Originally, it was my home page; now it's just at the top of my bookmarks. It's an html file; however, since Github doesn't allow attaching html files, I just changed the suffix.

**Comment by Boruch-Baum** [comment]
[w3m_cheat_sheet_page.txt](https://github.com/felipesaa/A-vim-like-firefox-like-configuration-for-w3m/files/2698315/w3m_cheat_sheet_page.txt)

**Comment by felipesaa** [comment]
Thank you
I have applied your corrections
I like the idea of having local documentation linked in the bookmarks
